### PR TITLE
Fix NMS code in latest 1.19.4 [Itemsadder / Oraxen things]

### PR DESCRIPTION
**Pull request by IPECTER**

### CODE REVIEW

**Comment by NextdoorPsycho** [comment]
are you unable to compile on 1.19.4? i am? whats your problem?

**Comment by IPECTER** [comment]
Recently 1.19.4 nms code was changed in CraftBukkit 1.19.4 Patch.
This pr is for supporting latest 1.19.4 bukkits

**Comment by NextdoorPsycho** [comment]
i manually did the nms thing, and im still looking for a better solution to the IA stuff, and i think vatuu did it, look at the DataProviders

**Comment by IPECTER** [comment]
thx!

**Pull request closed without merging**
