### PR TITLE
Rework /iris create & patch /iris pregen start

### PR DESCRIPTION
**Pull request by svdgoor**

### CODE REVIEW

**Comment by cyberpwnn** [comment]
Waiting on #515

**Comment by cyberpwnn** [comment]
As usual lol, conflicts

**Comment by svdgoor** [comment]
There's a problem where the resulting world is returned before it's actually existent, which results in NPEs when trying to print info, teleport the player & save it.
I tried delaying the get but failed, please send help

**Comment by cyberpwnn** [comment]
ill fix

**Pull request merged**
