### PR TITLE
WIP plague implementation

### PR DESCRIPTION
**Pull request by svdgoor**
I got it to compile.
Christ

### CODE REVIEW

**Comment by svdgoor** [comment]
Note to self: fix infinite optional / required parameters in parameter amount check
Vararg conversion
Tab complete suggestions in annotations

**Comment by cyberpwnn** [comment]
this is going to merge conflict into oblivion fyi

**Comment by svdgoor** [comment]
Should be fine considering I'm working in a totally separate packacke *for now*, but yes, if I start converting commands to Plague it'll get messy. I'll probably just wait for you at that point, or do it overnight (totally stable yes)

**Comment by svdgoor** [comment]
(Implemented through Decree)

**Pull request closed without merging**
