### PR TITLE
Prevent opening studio worlds twice close after eachother

### PR DESCRIPTION
**Pull request by svdgoor**

### CODE REVIEW

**Comment by cyberpwnn** [comment]
Why do we need this? You cant just put a variable there, Studio worlds run async from each other, slapping a bandaid variable over it isnt thread safe. Instead, get a future of the current studio world and close it, THEN open the new one possibly.

**Comment by svdgoor** [comment]
If you open two studio worlds neither open, you cannot open new ones, and you're stuck with the "generating" popup in your screen.
Not sure I follow about thread safety - considering that you can only send two commands _that_ fast after eachother... do you mean making it Atomic? Not sure how futures help with this.

**Comment by cyberpwnn** [comment]
A deadlock is happening, Iris cant be closed during a specific init phase, fixing that will fix it.

**Comment by cyberpwnn** [comment]
And no, the init phase is NOT thread safe, not talking about the boolean itself

**Comment by svdgoor** [comment]
Does enabling sync on the command fix that without slowing down the main thread, or should we figure out a better way to prevent another thread from starting incase another is already working?

**Comment by cyberpwnn** [comment]
No, the solution is a bit more complicated than setting something sync and blocking it by a boolean. I will fix it, in fact its mostly fixed already (a cache was clearing while accessing itself causing a deadlock).

**Pull request closed without merging**
