### PR TITLE
Remove dolphins so there's no crashes because of treasure chests.

### PR DESCRIPTION
**Pull request by svdgoor**
Implementation only disables dolphins, this is a poor fix, but afaik it requires Treasure chests to both spawn and be registered as spawned in the chunks' data files, which is beyond my understanding / grasp of Iris' internals.

### CODE REVIEW

**Comment by svdgoor** [comment]
#499

**Comment by svdgoor** [comment]
Before merging this add a check to if event.getlocation.getworld is an iris world

**Comment by StrangeOne101** [comment]
Why not just prevent people from feeding dolphins instead of stopping them from spawning? This seems pretty drastic...

**Comment by svdgoor** [comment]
Looks like there's indeed a better implementation.
I'll add support for disabling villagers' trades as well, while I'm at it.

**Comment by StrangeOne101** [comment]
Disabling villager trades?

**Comment by svdgoor** [comment]
Cartographer villagers can sell maps that point to mansions/monuments etc, I'm going to override exactly those trades

**Comment by svdgoor** [comment]
Preventing dolphins from interacting with items
Preventing villagers from showing cartographer trades by:
- Allowing to disable the explorer map trades altogether, or
- Overriding the trades with the default selection, or
- Overriding the trades with a custom selection, definable in the dimension file

**Review by StrangeOne101 — APPROVED** [review]

**Comment by svdgoor** [comment]
```
[11:43:06 INFO]: [Iris]: IrisDimension: Unsupported Type: org.bukkit.inventory.ItemStack Did you forget @Desc?
[11:43:06 INFO]: [Iris]: IrisDimension: Missing @Desc on field type (class org.bukkit.Material) in org.bukkit.inventory.ItemStack
[11:43:06 INFO]: [Iris]: IrisDimension: Missing @Desc on field amount (int) in org.bukkit.inventory.ItemStack
[11:43:06 INFO]: [Iris]: IrisDimension: Unsupported Type: org.bukkit.material.MaterialData Did you forget @Desc?
[11:43:06 INFO]: [Iris]: IrisDimension: Unsupported Type: byte Did you forget @Desc?
[11:43:06 INFO]: [Iris]: IrisDimension: Missing @Desc on field data (byte) in org.bukkit.material.MaterialData
[11:43:06 INFO]: [Iris]: IrisDimension: Missing @Desc on field data (class org.bukkit.material.MaterialData) in org.bukkit.inventory.ItemStack
[11:43:06 INFO]: [Iris]: IrisDimension: Unsupported Type: org.bukkit.inventory.meta.ItemMeta Did you forget @Desc?
[11:43:06 INFO]: [Iris]: IrisDimension: Missing @Desc on field meta (interface org.bukkit.inventory.meta.ItemMeta) in org.bukkit.inventory.ItemStack
```

There are unsupported types and missing descriptions on Bukkit enums & variables I cannot access.
I don't know how to prevent these errors. 
Note: The system works fully, I saw the trade in game, it's customizable from the dimension json, and autocompletions work.

**Pull request merged**
