### PR TITLE
Implementation of #692

### PR DESCRIPTION
**Pull request by xIRoXaSx**
Added timeBlock and weather to IrisCommand to allow commands only at specific times and weather conditions.

### CODE REVIEW

**Review by svdgoor — APPROVED** [review]
Looks good

**Comment by NextdoorPsycho** [comment]
Why would the dimension need to be in control of having commands go off at certain times?
thats not our job

**Comment by svdgoor** [comment]
So we can support any other plugin that does anything like spawning structures on command, custom entities, what not

**Comment by NextdoorPsycho** [comment]
dangerous but ok, i can see this being something thats helpful ig

**Comment by NextdoorPsycho** [comment]
ill merge this if you can show me its working

**Review by NextdoorPsycho — APPROVED** [review]

**Comment by NextdoorPsycho** [comment]
Works, Cool

**Pull request merged**
