### PR TITLE
Added studio trim command

### PR DESCRIPTION
**Pull request by StrangeOne101**
- Added studio trim command. Allows you to analyze/delete unused files in a project/pack

### CODE REVIEW

**Review by svdgoor — COMMENTED** [review]
It looks good apart from that it will be a bitch to upkeep.
Have your tried pregenerating a world with a timed pack?

**Comment by StrangeOne101** [comment]
Not yet. It will be a pain to upkeep, but that's fine. Some trim is better than none.

I haven't been able to test a trimmed pack yet because of the AtomicCache bug. Like 30% of all object keys are not loaded and are null, and this can even happen to some biomes or regions. If this happens, then it can't get an accurate grasp on what is used or what isn't. So it's being PRd now since its done, but just can't really be used until that bug is fixed

Edit: The idea was to reduce world sizes, though. Since the Iris folder in worlds is like 200mb right now

**Comment by svdgoor** [comment]
At least you're able to more reliably see the defected of the atomic cache bug

**Comment by StrangeOne101** [comment]
HAHAHAHA true true. It's actually what made me realize what the bug was.

It's also good for understanding it as running the analyze part will show you that some objects are fine, but the next time you run it, they can be affected. So it has nothing to do with any specific thing; the cache itself is the issue

**Comment by cyberpwnn** [comment]
Does this actually work or corrupt packs. TBH just do a word search for objects. We dont care about saving 1kb here and there for json files, objects are big trim those.

However we dont want to trim the main world because people contribute to it. It would be a pain to constantly have to add content back in to use it instead of having the library right there at your fingertips, the cost is small, its not too bad to have everyone download it.

**Comment by NextdoorPsycho** [comment]
The only reason i see this being helpful is when we / if we start like uploading and sharing packs
Can you confirm if it is working as of now @StrangeOne101 ?

**Comment by NextdoorPsycho** [comment]
i want to try this on development and see practicality

**Pull request merged**
