### PR TITLE
Pregen fix: exclude custom biome from id mapping

### PR DESCRIPTION
**Pull request by covoge**
This is a (quick and dirty) fix that enables pregen on the newest purpur builds.

1.16.5 introduced a new biome called "CUSTOM" for which no biome base can be found (NMSBinding16_3:30). This causes an exception when trying to add it to the biome base cache. I excluded this new custom biome from the biome id computation so this problem doesn't occur anymore. I haven't done much research on why this biome base doesn't exist, but we might want to look into what causes it for a better fix in a future release.

For this change I needed to bump the spigot api dependency to version 1.16.5-R0.1 which causes some additional changes in other classes.

This PR also includes further changes in the pom that update the volmit repository url to use HTTPS ~~and bumps the compiler source and target levels to 11.~~ If you don't like these changes I can also roll them back.

I would greatly appreciate any feedback from you guys.

### CODE REVIEW

**Review by svdgoor — COMMENTED** [review]
Looks good other than that there are a lot of added functions in other files, for which I fail to see the use.

**Comment by covoge** [comment]
Those are needed overrides caused by changes in the respective superclasses - they were added somewhere between 1.16.1-R0.1 and the new 1.16.5-R0.1

**Comment by svdgoor** [comment]
Alright, thanks for the clarification. @cyberpwnn can merge it after doublechecking my assessment.
Thank you for the contribution!

**Comment by covoge** [comment]
My pleasure! I've been following the project for quite some time now and since I currently have some time on my hands I was looking into contributing and fixing some of the existing issues.

**Comment by cyberpwnn** [comment]
Thanks @pazkaI

**Pull request merged**
