### PR TITLE
Recoloring command for broken custom colors WIP

### PR DESCRIPTION
**Pull request by svdgoor**
Users have been having trouble with custom colors going away after some time for (as far as my knowledge goes) unknown reasons.
To to help those that lose their colors get them back this PR introduces a new command: `/recolor <radius=5>`.
Please take a look at the code and properly test it. I am having dependency issues so I have not been able to test the code myself. WIP / UNTESTED

### CODE REVIEW

**Comment by svdgoor** [comment]
Managed to get it running.
It currently just replaces the chunks as it would with the normal `/iris regen`.
I'll see if I can figure this out.

**Comment by svdgoor** [comment]
Progress. Ran the wrong function...

**Comment by svdgoor** [comment]
Still not working... my current thoughts are that I need to provide the entire chunk.
Though now looking at it, I'm noticing /iris regen isn't providing the custom biomes either. I'll look into this more.

**Comment by NextdoorPsycho** [comment]
Because if you are using the headless system custom colors are not being stored properly. But also you can't do a radius. It's every chunk. Any chunk that was ever loaded lost the colors. You need to redo ALL colors. and that would kill the server. So do you see now why I wanted to just prevent this from happening in the first place? If you can still manage it I'll still approve it. But you gotta get every chunk

**Comment by svdgoor** [comment]
Headless is disabled on latest, so no I'm not

**Comment by svdgoor** [comment]
And it wouldn't crash the server if distributed properly like done with the regen command.
That command is technically capable of regenning the entire world in one go without crashing.

**Comment by svdgoor** [comment]
The reason I'm using the radius is so I can test to see if I can inject the colors after the biome was already generated.
This is in no way the final product.

**Comment by svdgoor** [comment]
And I agree it shouldn't happen. But this at least allows those that had the issue to update and fix their colors.

**Comment by svdgoor** [comment]
I'm kinda giving up on this one tbh. If anyone wants to continue this, good luck!

**Pull request closed without merging**
