### PR TITLE
Update IrisProject.java

### PR DESCRIPTION
**Pull request by svdgoor**

### CODE REVIEW

**Comment by svdgoor** [comment]
Removes the weather and daylight cycle from studio worlds

**Comment by cyberpwnn** [comment]
This should be configurable

**Comment by svdgoor** [comment]
@cyberpwnn Updated to be configurable. Default set to true since I don't see a reason why someone would want weather and daylight cycling in their studio world.

**Comment by svdgoor** [comment]
Hope I did this right, haven't worked with Iris' settings thus far

**Pull request merged**
