### PR TITLE
Undo a change that breaks when Biome.CUSTOM is not a field on your MC Distribution

### PR DESCRIPTION
**Pull request by svdgoor**

### CODE REVIEW

**Comment by cyberpwnn** [comment]
### **Situation 1** 
Biome.CUSTOM exist and somehow causes NMS issues because it doesnt have a backing CraftBiome or whatever, causes issues when Iris loops over it for DirectWrite MCA gens

### **Situation 2**
Biome.CUSTOM does NOT exist, so checking for it just crashes anyways because its not defined

### **Solution**
```java
private static Map<Biome, Integer> computeBiomeIDs() {
    Map<Biome, Integer> biomeIds = new KMap<>();

    for(Biome biome : Biome.values())
    {
        if (!biome.name().equals("CUSTOM")) {
            biomeIds.put(biome, INMS.get().getBiomeId(biome));
        }
    }

    return biomeIds;
}
```

**Comment by svdgoor** [comment]
As requested. :D

**Comment by svdgoor** [comment]
Included in PR #366. You can still merge this if that one doesn't suit you.

**Comment by cyberpwnn** [comment]
Next time just

**Pull request merged**
