### PR TITLE
Added Object & Jigsaw Loot Tables

### PR DESCRIPTION
**Pull request by StrangeOne101**
- Added the ability for placed objects and jigsaws to have select loot tables
    - Includes the ability to filter loot tables based on block type/block state
    - Overrides loot tables from the biome/region, but if no loot tables are provided for an object, they will still be used
    - Uses weight based system for determining which table to pick (so it's guaranteed rather than by chance)
- Added WeightedRandom util class
- Fixed object find and replace overriding existing block state properties when just editing a block of the same type (end portal frame -> end portal frame with eye). This allows things to keep their orientation when changing a single property.
- Fixed loot tables not being random based on the seed
- Fixed jigsaws breaking bedrock
- Fixed enchantments in loot tables not working for enchanted books
- Fixed mobs spawned in Jigsaws not being spawned in the center like they should be

### CODE REVIEW

**Comment by StrangeOne101** [comment]
Note: I _occasionally_ got this exception when running this build on paper. About 1/6 times. It happened when a studio world was created when an object that has loot spawns naturally.
```
[22:55:19] [Iris Generator 3/WARN]: java.util.ConcurrentModificationException
[22:55:19] [Iris Generator 3/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1225)
[22:55:19] [Iris Generator 3/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.toBukkit(CraftBlockData.java:154)
[22:55:19] [Iris Generator 3/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.get(CraftBlockData.java:64)
[22:55:19] [Iris Generator 3/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftRotatable.getAxis(CraftRotatable.java:22)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.object.IrisObjectRotation.rotate(IrisObjectRotation.java:292)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.object.IrisObject.place(IrisObject.java:676)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.scaffold.engine.EngineParallaxManager.place(EngineParallaxManager.java:561)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.scaffold.engine.EngineParallaxManager.place(EngineParallaxManager.java:511)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.scaffold.engine.EngineParallaxManager.generateParallaxSurface(EngineParallaxManager.java:442)
[22:55:19] [Iris Generator 3/WARN]: 	at com.volmit.iris.scaffold.engine.EngineParallaxManager.generateParallaxLayer(EngineParallaxManager.java:311)
```
...Yep. This kind of error. I can't see directly how this can be caused, since everything does use ConncurrentHashMaps (KMaps) and it isn't even my code that is mentioned. 

My best guess is that while the cache for the loot tables is building, other parts of the Jigsaw are still building - causing this exception. 

Thought it'd be a good idea just to mention it so this isn't released without testing. If anyone has any insight or fixes, please do share since I'm unsure on what to do about it.

**Comment by StrangeOne101** [comment]
I've just noticed that the error above still happens on Iris 1.3.11, so I think it's possible it's just completely unrelated

**Comment by svdgoor** [comment]
Yeah It's been there for a good while now. Usually just Iris taking more CPU than there is. You can decrease the number of threads in the config, which will improve this.

**Comment by StrangeOne101** [comment]
RIP Iris on my i7-6700 lol. I got it set to -1 threads right now so it should just be using as many threads as there are. Oh well. Good to know that it isn't my code I guess

**Pull request merged**
