### PR TITLE
Change "height" string

### PR DESCRIPTION
**Pull request by ghost**
Changes the height from 256 to the actual 384 height that is used in 1.18 by iris
See https://github.com/VolmitSoftware/Iris/issues/749

### CODE REVIEW

**Comment by ghost** [comment]
@CocoTheOwner Is it okay to change it to 384 cause mathematically its -64 to 320 but we know how people sometimes are lol

**Comment by svdgoor** [comment]
If only I could merge this lol

**Comment by ghost** [comment]
@NextdoorPsycho Either this or just remove the reference of the height at all

**Comment by NextdoorPsycho** [comment]
Have you tested this. Does this work?

**Comment by NextdoorPsycho** [comment]
Made a different fix, and now we show the range

**Pull request closed without merging**
